<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BibliotecaConversao">
      <HintPath>..\MinhaBiblioteca\bin\Debug\net8.0\BibliotecaConversao.dll</HintPath>
    </Reference>
    <Reference Include="BibliotecaFinanceira">
      <HintPath>..\BibliotecaFinanceira\bin\Debug\net8.0\BibliotecaFinanceira.dll</HintPath>
    </Reference>
    <Reference Include="BibliotecaValidacoes">
      <HintPath>..\BibliotecaValidacoes\bin\Debug\net8.0\BibliotecaValidacoes.dll</HintPath>
    </Reference>
    <Reference Include="DLLdoBetinha">
      <HintPath>..\..\..\..\Downloads\DLLdoBetinha.dll</HintPath>
    </Reference>
    <Reference Include="MinhaBiblioteca">
      <HintPath>..\MinhaBiblioteca\bin\Debug\net8.0\MinhaBiblioteca.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
